name = "ciscoprinters-website"
compatibility_date = "2026-08-18"

[assets]
directory = "."
binding = "ASSETS"

[env.production]
routes = ["ciscoprinters.co.ke/*", "www.ciscoprinters.co.ke/*"]

[env.preview]
routes = ["ciscoprinters-website.pages.dev/*"]